sudo: required
services:
   - docker
before_install:
   - docker build -t godfather0309/frontend -f Dockerfile.dev .

scripts:
   - docker run -e CI=true godfather0309/frontend npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "frontend"
   env:  "Frontend-env"
   bucket_name: "elasticbeanstalk-us-east-2-462152912253"
   bucket_path: "frontend"
   on:
    branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
    secure: "$AWS_SECRET_KEY"





    #Frontend-env.sreabub7wm.us-east-2.elasticbeanstalk.com