version : '3'
services: 
 web:
  build: 
    context: .                              # rather than just using build: . , we are going to use context to use Docerfile.dev
    dockerfile: Dockerfile.dev
  ports :
   - "3000:3000"
  volumes:
   - /app/node_modules
   - .:/app
 tests:
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - /app/node_modules
    - .:/app
  command: ["npm","run","test"]
